### ISSUE TITLE
discovery.etcd.io expired cert 2024-05-10

### ISSUE THREAD

**Issue by waipeng** [etcd-io/discovery.etcd.io#80]
Thanks for maintaining this service.

If this is not already known, https://discovery.etcd.io/ has an expire cert at the moment
```
$ openssl s_client -servername discovery.etcd.io -connect 35.225.64.149:443 2>/dev/null | openssl x509 -noout -dates
notBefore=Feb 10 12:43:27 2024 GMT
notAfter=May 10 12:43:26 2024 GMT
```

**Comment by waipeng** [comment]
Pinging @eduartua as they fixed this in #55. Thanks!

**Comment by eduartua** [comment]
Hey @waipeng thanks for the ping. 
The ingress resource is using both hosts `discovery.etcd.io` and `www.discovery.etcd.io`. Checking on the `cert-manager` pods I can see the error message `dial tcp: lookup www.discovery.etcd.io on 10.128.128.10:53: no such host` which indicates that the DNS lookup for www.discovery.etcd.io failed. Also, with `dig` we are getting non-existent domain:

```
dig  www.discovery.etcd.io

; <<>> DiG 9.18.25 <<>> www.discovery.etcd.io
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NXDOMAIN, id: 31045
;; flags: qr rd ra; QUERY: 1, ANSWER: 0, AUTHORITY: 1, ADDITIONAL: 1
```

 This could be due to various reasons such as a misconfigured DNS server. Maybe the DNS configuration changed recently? We need to validate this with the team responsible to manage the DNS config for `etcd.io`.

As this was affecting the production service, I modified the `Certificate` resource deleting the `www` hostname to get a valid certificate just for `discovery.etcd.io`.
```
openssl s_client -servername discovery.etcd.io -connect 35.225.64.149:443 2>/dev/null | openssl x509 -noout -dates
Warning: Reading certificate from stdin since no -in or -new option is given
notBefore=May 12 23:57:27 2024 GMT
notAfter=Aug 10 23:57:26 2024 GMT
```

After learning the status of the DNS configuration, we can revert to include `www` or we can send in a PR to delete the hostname from the ingress stanza in the helm chart values.

@etcd-io/maintainers-discovery @etcd-io/maintainers-etcd

**Comment by waipeng** [comment]
Hi @eduartua , many thanks for the quick fix!

**Comment by jmhbnz** [comment]
Looks like a side effect of the migration to managing `etcd.io` dns configuration as code as part of kubernetes and sig-etcd.  

The configuration for `etcd.io` dns is managed here https://github.com/kubernetes/k8s.io/blob/main/dns/zone-configs/etcd.io._0_base.yaml#L74 if you need to request any amendments @eduartua. Happy to provide a quick /lgtm if so.

**Comment by eduartua** [comment]
> Looks like a side effect of the migration to managing `etcd.io` dns configuration as code as part of kubernetes and sig-etcd.
> 
> The configuration for `etcd.io` dns is managed here https://github.com/kubernetes/k8s.io/blob/main/dns/zone-configs/etcd.io._0_base.yaml#L74 if you need to request any amendments @eduartua. Happy to provide a quick /lgtm if so.

Thanks. I have created this [PR](https://github.com/kubernetes/k8s.io/pull/6806)

**Comment by eduartua** [comment]
Certificate resource is now using both `discovery.etcd.io` and `www.discovery.etcd.io`:
```
openssl s_client -servername discovery.etcd.io -connect 35.225.64.149:443 2>/dev/null | openssl x509 -noout -dates
Warning: Reading certificate from stdin since no -in or -new option is given
notBefore=May 13 16:24:31 2024 GMT
notAfter=Aug 11 16:24:30 2024 GMT
```

and
```
openssl s_client -servername www.discovery.etcd.io -connect 35.225.64.149:443 2>/dev/null | openssl x509 -noout -dates                                                                          ✔  18:53:04 
Warning: Reading certificate from stdin since no -in or -new option is given
notBefore=May 13 16:24:31 2024 GMT
notAfter=Aug 11 16:24:30 2024 GMT
```

We can close this one.
